general:
  basename: /storage/28
  initial_states: null
  n_iterations: 1000
  num_replicas: 4
  output_path: optimization_run0
local_sampling:
  adaption_downrate: 0.95
  adaption_uprate: 1.05
  num_adaption_samples: 100
  num_steps: 20
  sampler: naive_hmc
  stepsizes: null
re:
  dump_interval: 500
  dump_step: 5
  schedule: schedule.pickle
  statistics_update_interval: 50
  status_interval: 100
  swap_interval: 5
